services:
  db:
    container_name: flownote_db
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: flownote
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: flownote_backend
    build:
      context: ./backend/flownote-backend/
      dockerfile: Dockerfile
    env_file:
      - ./backend/flownote-backend/.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://db:27017/flownote
      PORT: 3000
    ports:
      - "3000:3000"

  frontend:
    container_name: flownote_frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  db_data:
